# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNHttpServer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNHttpServer
  pod "GCDWebServer", "~> 3.5.3"

end
